# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d6ba578aa11e024d6310dff3245e52a71691ad88555f717770704aeb4f0fdc2cb77ee40326f2cafaaa4c3cb5d394176f10ce48d4bdd326ef36846b6181b5220

test:
  secret_key_base: 36f41aa25a211177719b9259c17ca070520db7bd1979fe0fc8f77bff731ac6969a42bef42a993e4ba2390c6f5f0f03b190d66d70134e83ed33a6150fc60d53ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
